import random
from Art import hangman_pics

# word list for the game (random words generated by ChatGPT :D)
word_list = ["python", "hangman", "challenge", "programming", "developer", "keyboard", "function", "variable"]
max_tries = 7

# function to get a random word
def get_random_word(word_list: list[str]) -> str:
    return random.choice(word_list)

# function to display the current word progress
def display_word_progress(word: str, guessed_letters: set[str]) -> str:
    return " ".join([letter if letter in guessed_letters else "_" for letter in word])

# function to display the current hangman state
def display_hangman_state(tries: int):
    print(hangman_pics[tries])

# main function
def play_hangman():
    word = get_random_word(word_list)
    guessed_letters = set()
    wrong_guesses = 0

    print("Welcome to Hangman!")

    while wrong_guesses < max_tries:
        display_hangman_state(wrong_guesses)
        print("Word:", display_word_progress(word, guessed_letters))
        print(f"Guessed letters: {', '.join(sorted(guessed_letters))}")

        guess = input("Enter a letter: ").lower()

        if not guess.isalpha() or len(guess) != 1:
            print("Invalid input. Please enter a single alphabet letter.")
            continue

        if guess in guessed_letters:
            print("You already guessed that letter. Try again.")
            continue

        guessed_letters.add(guess)

        if guess in word:
            print("Correct!")
            if all(letter in guessed_letters for letter in word):
                print("\nCongratulations! You guessed the word:", word)
                break
        else:
            print("Wrong!")
            wrong_guesses += 1

    else:
        display_hangman_state(wrong_guesses)
        print("\nGame Over! The word was:", word)

play_hangman()
